### ISSUE TITLE
asYouType issue on Chrome browser on Android device

### ISSUE THREAD

**Issue by srichandradeep** [catamphetamine/libphonenumber-js#105] opened 2017-08-09 14:01 UTC
Hi,

I see asYouType isn't working properly on Chrome browser version > 59.x on Android devices. For example, I have selected country as +1. When I type the number, as soon as the 1st special character (i.e. a space in this case) has been displayed then, the next typed digit is getting added before the special character instead of getting appended after the special character.
This is reproducible even in provided demo example.
Can you please look into this?
Thanks.

**Comment by catamphetamine** [comment] 2017-08-09 14:02
I can look into this if you post here the exact steps to reproduce the issue

**Comment by srichandradeep** [comment] 2017-08-10 09:03
1. Navigate to https://catamphetamine.github.io/libphonenumber-js/.
2. Clear the default number under the section, As you type.
3. Now try to type "+12133734253". If you observe, you'll end up in typing "+1 133 342 3572" instead of "+1 213 373 4253" (Do not move the typing cursor manually).
Tested on the below two devices.
1. Device used:  Galaxy Tab S.
Model #: SM-T805
Android version: 6.0.1
Chrome version#: 59.0.3071.125. Also tested in latest Chrome Beta version#, 60.0.3112.78.
2. Device used:  Galaxy Edge S6.
Android version: 7.0
Chrome version#: 59.0.3071.125. Also tested in latest Chrome Beta version#, 60.0.3112.78.

**Comment by catamphetamine** [comment] 2017-08-10 09:18
Maaan, test it on a normal computer.

**Comment by srichandradeep** [comment] 2017-08-10 09:30
Ha ha, it's working fine on a PC or a laptop.

Thanks and regards,
Srichandradeep C

**Comment by catamphetamine** [comment] 2017-08-10 09:47
There was a bug related to Samsung Android phones when using `type="tel"`.
I changed it from `type="tel"` to `type="text"` in the demo.
It's supposed to work on Android phones now
https://github.com/catamphetamine/libphonenumber-js/issues/105#issuecomment-321501098

**Comment by srichandradeep** [comment] 2017-08-21 10:07
Not working on your demo site. Tested just now.

**Comment by catamphetamine** [comment] 2017-10-09 18:26
@srichandradeep Yes, because in the new version it's back to `type="tel"` again.
The reason is that I won't tolerate Android developers forcing everyone else to fix their bugs for them.
One can specify `<Phone type="text"/>` manually to see if it resolves the issue.
But in this case a mobile user will have to input using the standard textual keyboard while when using proper `type="tel"` attribute the user (theoretically) will just get the digital keyboard to input the phone number which is much better User Experience.
I'm opening this issue since other people may be experiencing this (and seems that they are).

**Comment by Subha** [comment] 2017-10-09 19:37
Thank you for the response. Yes I noticed the issue even without me defaulting the type to 'tel'. Also we have a UI requirement to have TEL Pad for mobile users. . Any other suggestions.?

**Comment by catamphetamine** [comment] 2017-10-09 19:46
People are having issues with Android.
Like this: https://github.com/catamphetamine/input-format/issues/2
It's an issue for `input-format` which is the base library for this one.
I don't have any suggestions for you: seems that this library is not guaranteed to be compatible with all Android devices out there.
Perhaps I could even try something to fix this but I don't have such an Android device at my disposal (only an iPhone).

**Comment by Subha** [comment] 2017-10-09 20:26
Let me try to find an emulator and look at this issue. Thank you

**Comment by catamphetamine** [comment] 2017-10-13 13:26
Closing this one because it's `input-format` issue and unrelated to this library

**Closed by catamphetamine** 2017-10-13 13:26 UTC
